/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description 恢复有效浏览器 Session，或创建独立游客 Session。
         */
        get: operations["get_session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 验证游客请求并原子消费邀请码创建账号与工作区。
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 验证账号后撤销游客 Session，并轮换为注册用户 Session。
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 撤销注册 Session，并为当前浏览器建立全新游客 Session。
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description 列出当前账号或游客 Session 自己的活动/归档会话。
         */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description 为当前服务端 Principal 创建并持久绑定随机 thread。
         */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Chat Message
         * @description 验证 thread 归属后执行一轮唯一主图并返回公开结果。
         */
        post: operations["send_chat_message_api_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/pending-l2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending L2
         * @description 授权后返回当前 conversation 的有限 L2 待处理卡片。
         */
        get: operations["get_pending_l2_api_conversations__thread_id__pending_l2_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/l2-upgrade-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide L2 Upgrade
         * @description 验证预览绑定、接受决定，并在后台恢复升级流程。
         */
        post: operations["decide_l2_upgrade_api_conversations__thread_id__l2_upgrade_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/l2-memory-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide L2 Memory
         * @description 验证偏好建议绑定、接受决定，并在后台恢复 Memory 流程。
         */
        post: operations["decide_l2_memory_api_conversations__thread_id__l2_memory_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/pending-refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Refund
         * @description 授权后返回当前 thread 可见且仍在等待决定的退款预览。
         */
        get: operations["get_pending_refund_api_conversations__thread_id__pending_refund_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/refund-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Refund
         * @description 验证绑定退款动作、接受决定，并在后台恢复同一 Graph task。
         */
        post: operations["decide_refund_api_conversations__thread_id__refund_approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 返回当前身份可访问的会话摘要与待处理状态。
         */
        get: operations["get_conversation_api_conversations__thread_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description 先写 deleting 墓碑，再清理 Checkpoint 和公开交互数据。
         */
        delete: operations["delete_conversation_api_conversations__thread_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Lifecycle
         * @description 允许注册用户归档或恢复本人会话，游客不维护归档列表。
         */
        patch: operations["update_lifecycle_api_conversations__thread_id__patch"];
        trace?: never;
    };
    "/api/conversations/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description 分页返回持久公开历史，不读取或反序列化 Checkpoint 消息。
         */
        get: operations["list_messages_api_conversations__thread_id__messages_get"];
        put?: never;
        /**
         * Submit Message
         * @description 原子接受消息后独立执行 Graph，并立即返回可查询 Run。
         */
        post: operations["submit_message_api_conversations__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description 读取授权会话中指定 Run 的当前公开状态。
         */
        get: operations["get_run_api_conversations__thread_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Run
         * @description 仅对 failed/interrupted Run 创建一次显式、幂等的新执行。
         */
        post: operations["retry_run_api_conversations__thread_id__runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{thread_id}/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description 重放缺失事件并跟随当前 Run，终态送达后关闭 SSE。
         */
        get: operations["stream_run_events_api_conversations__thread_id__runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/l2-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List L2 Cases
         * @description 按最近更新时间列出当前账号自己的 L2 Case。
         */
        get: operations["list_l2_cases_api_l2_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/l2-cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get L2 Case
         * @description 返回本人指定 Case 及脱敏公开轨迹，越权与不存在统一为 404。
         */
        get: operations["get_l2_case_api_l2_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/l2-cases/{case_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get L2 Case Trace
         * @description 按 Case 内单调序号只读回放本人公开 Trace，不执行 Graph。
         */
        get: operations["get_l2_case_trace_api_l2_cases__case_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description 从当前账号独立 namespace 返回最多三类已确认偏好。
         */
        get: operations["list_memories_api_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Memory
         * @description 删除本人指定偏好；越权或不存在不泄露其他 namespace。
         */
        delete: operations["remove_memory_api_memories__memory_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Memory
         * @description 只纠正本人既有偏好的受限枚举值，并保留来源 Case。
         */
        patch: operations["update_memory_api_memories__memory_id__patch"];
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orders
         * @description 列出当前注册用户私有工作区中的订单与物流。
         */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /**
         * Create Order
         * @description 在当前注册用户私有工作区创建订单及可选物流。
         */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Order
         * @description 删除当前工作区指定订单及其物流，并统一越权错误。
         */
        delete: operations["delete_order_api_orders__order_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Order
         * @description 更新当前工作区指定订单与一对一物流记录。
         */
        patch: operations["update_order_api_orders__order_id__patch"];
        trace?: never;
    };
    "/api/orders/{order_id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert Payment
         * @description 为当前注册用户订单创建或更新退款前 Mock 支付事实。
         */
        put: operations["upsert_payment_api_orders__order_id__payment_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Refunds
         * @description 列出当前注册用户指定私有订单的全部 Mock 退款结果。
         */
        get: operations["list_refunds_api_orders__order_id__refunds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentRunResponse
         * @description 返回授权会话中的当前 Run 状态。
         */
        AgentRunResponse: {
            run: components["schemas"]["PublicAgentRun"];
        };
        /**
         * AsyncChatMessageRequest
         * @description 接收客户端稳定请求 ID 和一条新用户消息。
         */
        AsyncChatMessageRequest: {
            /** Client Message Id */
            client_message_id: string;
            /** Message */
            message: string;
        };
        /**
         * ChatMessageRequest
         * @description 接收当前 thread 和一条用户消息。
         */
        ChatMessageRequest: {
            /** Thread Id */
            thread_id: string;
            /** Message */
            message: string;
        };
        /**
         * ChatResponse
         * @description 返回一轮 Graph 的公开消息、状态和政策引用。
         */
        ChatResponse: {
            /** Thread Id */
            thread_id: string;
            /** Assistant Message */
            assistant_message: string;
            /** Public Status */
            public_status: string;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["PolicyCitation"][];
            refund_preview?: components["schemas"]["PublicRefundPreview"] | null;
            refund_result?: components["schemas"]["PublicRefundResult"] | null;
            l2_upgrade_preview?: components["schemas"]["PublicL2UpgradePreview"] | null;
            l2_case_summary?: components["schemas"]["PublicL2CaseSummary"] | null;
            /** L2 Pending Action */
            l2_pending_action?: ("upgrade_confirmation" | "user_input" | "memory_confirmation" | "refund_approval") | null;
            /**
             * L2 Trace Events
             * @default []
             */
            l2_trace_events: components["schemas"]["PublicL2TraceEvent"][];
            memory_proposal?: components["schemas"]["PublicMemoryProposal"] | null;
        };
        /**
         * ConversationDetailResponse
         * @description 返回会话摘要及当前公开待处理动作。
         */
        ConversationDetailResponse: {
            conversation: components["schemas"]["ConversationSummary"];
        };
        /**
         * ConversationLifecycleRequest
         * @description 只允许在 active 与 archived 两种公开生命周期间切换。
         */
        ConversationLifecycleRequest: {
            /**
             * Lifecycle Status
             * @enum {string}
             */
            lifecycle_status: "active" | "archived";
        };
        /**
         * ConversationListResponse
         * @description 返回当前身份可见的会话列表和下一页游标。
         */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ConversationMessage
         * @description 表示可向当前会话所有者公开的一条持久消息。
         */
        ConversationMessage: {
            /** Message Id */
            message_id: string;
            /** Thread Id */
            thread_id: string;
            /** Run Id */
            run_id?: string | null;
            /** Sequence No */
            sequence_no: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "action" | "status";
            /** Content */
            content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "completed" | "failed";
            /**
             * Payload Version
             * @default 1
             */
            payload_version: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationMessagesResponse
         * @description 返回按序号递增的公开消息页和历史完整性状态。
         */
        ConversationMessagesResponse: {
            /** Messages */
            messages: components["schemas"]["ConversationMessage"][];
            /**
             * History State
             * @enum {string}
             */
            history_state: "complete" | "partial";
            /** Next After Sequence */
            next_after_sequence?: number | null;
        };
        /**
         * ConversationResponse
         * @description 返回当前身份新建的随机 conversation thread。
         */
        ConversationResponse: {
            /** Thread Id */
            thread_id: string;
        };
        /**
         * ConversationSummary
         * @description 表示会话列表和详情共同使用的公开生命周期摘要。
         */
        ConversationSummary: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
            /**
             * Lifecycle Status
             * @enum {string}
             */
            lifecycle_status: "active" | "archived" | "deleting" | "deleted";
            /**
             * History State
             * @enum {string}
             */
            history_state: "complete" | "partial";
            /** Message Count */
            message_count: number;
            /** Last Message Preview */
            last_message_preview?: string | null;
            /** Last Message At */
            last_message_at?: string | null;
            /** Pending Action */
            pending_action?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Archived At */
            archived_at?: string | null;
        };
        /**
         * DeleteResponse
         * @description 返回确定性删除操作的公开结果。
         */
        DeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * L2CasesResponse
         * @description 返回当前账号最近的 L2 Case 列表。
         */
        L2CasesResponse: {
            /** Cases */
            cases: components["schemas"]["PublicL2CaseSummary"][];
        };
        /**
         * L2ContextPublicSummary
         * @description 表示可以投影给用户的有限上下文来源和处理结果。
         */
        L2ContextPublicSummary: {
            /**
             * Source Types
             * @default []
             */
            source_types: ("control" | "case_goal" | "public_message" | "business_observation" | "policy_observation" | "confirmed_preference")[];
            /** Selected Count */
            selected_count: number;
            /**
             * Public Evidence Ids
             * @default []
             */
            public_evidence_ids: string[];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Facts Refreshed
             * @default 0
             */
            facts_refreshed: number;
            /**
             * State Changed
             * @default false
             */
            state_changed: boolean;
            /**
             * Essential Complete
             * @default true
             */
            essential_complete: boolean;
        };
        /**
         * L2MemoryDecisionRequest
         * @description 只允许客户端确认或拒绝当前 Case 的受限偏好建议。
         */
        L2MemoryDecisionRequest: {
            /** Proposal Id */
            proposal_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "reject";
        };
        /**
         * L2UpgradeDecisionRequest
         * @description 只允许客户端确认或取消服务端已保存的升级预览。
         */
        L2UpgradeDecisionRequest: {
            /** Preview Id */
            preview_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "cancel";
        };
        /**
         * LoginRequest
         * @description 接收账号登录凭据。
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * MemoriesResponse
         * @description 返回当前账号三类受限长期偏好。
         */
        MemoriesResponse: {
            /** Memories */
            memories: components["schemas"]["PublicCustomerPreference"][];
        };
        /**
         * MemoryUpdateRequest
         * @description 只接收目标偏好的新受限枚举值。
         */
        MemoryUpdateRequest: {
            /**
             * Value
             * @enum {string}
             */
            value: "zh-CN" | "en" | "concise" | "standard" | "detailed" | "neutral" | "friendly";
        };
        /**
         * MockPaymentInput
         * @description 校验注册用户为演示订单维护的退款前 Mock 支付事实。
         */
        MockPaymentInput: {
            /** Amount */
            amount: string;
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /**
             * Channel
             * @enum {string}
             */
            channel: "mock_card" | "mock_wallet";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "settled" | "failed";
        };
        /**
         * OrderCreate
         * @description 校验私有工作区中新建订单及可选物流。
         */
        OrderCreate: {
            /** Order Id */
            order_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "shipped" | "delivered" | "cancelled";
            shipment?: components["schemas"]["ShipmentInput"] | null;
        };
        /**
         * OrderUpdate
         * @description 校验订单与物流的部分更新，至少要求一个字段。
         */
        OrderUpdate: {
            /** Status */
            status?: ("processing" | "shipped" | "delivered" | "cancelled") | null;
            shipment?: components["schemas"]["ShipmentInput"] | null;
            /**
             * Remove Shipment
             * @default false
             */
            remove_shipment: boolean;
        };
        /**
         * OrdersResponse
         * @description 返回当前私有工作区订单列表。
         */
        OrdersResponse: {
            /** Orders */
            orders: components["schemas"]["PublicOrder"][];
        };
        /**
         * PendingL2Response
         * @description 返回 conversation 当前是否存在 L2 结构化待处理动作。
         */
        PendingL2Response: {
            /** Pending */
            pending: boolean;
            /** Public Status */
            public_status: string;
            /** Pending Action */
            pending_action?: string | null;
            upgrade_preview?: components["schemas"]["PublicL2UpgradePreview"] | null;
            memory_proposal?: components["schemas"]["PublicMemoryProposal"] | null;
        };
        /**
         * PendingRefundResponse
         * @description 返回当前 conversation 是否存在可决定的待审批退款。
         */
        PendingRefundResponse: {
            /** Pending */
            pending: boolean;
            /** Public Status */
            public_status: string;
            refund_preview?: components["schemas"]["PublicRefundPreview"] | null;
        };
        /**
         * PolicyCitation
         * @description 保存能够解析回确定政策原文的服务端引用。
         */
        PolicyCitation: {
            /** Document Id */
            document_id: string;
            /** Title */
            title: string;
            /** Version */
            version: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
            /** Section Id */
            section_id: string;
            /** Heading */
            heading: string;
            /** Source Relative Path */
            source_relative_path: string;
            /** Line Start */
            line_start: number;
            /** Line End */
            line_end: number;
            /** Content Hash */
            content_hash: string;
        };
        /**
         * PublicAgentRun
         * @description 向当前会话所有者公开 Run 状态，不披露请求摘要和 Checkpoint 标识。
         */
        PublicAgentRun: {
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /** Client Request Id */
            client_request_id: string;
            /**
             * Request Kind
             * @enum {string}
             */
            request_kind: "chat_message" | "refund_decision" | "l2_upgrade_decision" | "memory_decision" | "retry";
            /** Retry Of Run Id */
            retry_of_run_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "running" | "waiting_action" | "completed" | "failed" | "interrupted";
            /** Pending Action */
            pending_action?: string | null;
            /** Public Error Code */
            public_error_code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PublicCustomerPreference
         * @description 返回用户可以查看、纠正和删除的单条确认偏好。
         */
        PublicCustomerPreference: {
            /** Memory Id */
            memory_id: string;
            /** Memory Type */
            memory_type: string;
            /** Value */
            value: string;
            /** Source Case Id */
            source_case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Confirmed At
             * Format: date-time
             */
            last_confirmed_at: string;
        };
        /**
         * PublicL2CaseDetail
         * @description 返回授权 Case 摘要和有界公开轨迹。
         */
        PublicL2CaseDetail: {
            case: components["schemas"]["PublicL2CaseSummary"];
            /** Events */
            events: components["schemas"]["PublicL2TraceEvent"][];
            metrics: components["schemas"]["PublicL2CaseMetrics"];
            /** Next After Sequence */
            next_after_sequence?: number | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /**
         * PublicL2CaseMetrics
         * @description 返回理解 Case 资源和上下文质量所需的有限聚合指标。
         */
        PublicL2CaseMetrics: {
            /** Steps */
            steps: number;
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            /** Candidate Count */
            candidate_count: number;
            /** Selected Count */
            selected_count: number;
            /** Duplicate Count */
            duplicate_count: number;
            /** Stale Count */
            stale_count: number;
            /** Conflict Count */
            conflict_count: number;
            /** Truncated Count */
            truncated_count: number;
            /** Candidate Estimated Tokens */
            candidate_estimated_tokens: number;
            /** Selected Estimated Tokens */
            selected_estimated_tokens: number;
            /** Provider Input Tokens */
            provider_input_tokens: number;
            /** Provider Output Tokens */
            provider_output_tokens: number;
            /** Usage Sources */
            usage_sources: string[];
            /** Context Duration Ms */
            context_duration_ms: number;
            /** Model Duration Ms */
            model_duration_ms: number;
            /** Tool Duration Ms */
            tool_duration_ms: number;
            /** Case Duration Ms */
            case_duration_ms: number;
        };
        /**
         * PublicL2CaseSummary
         * @description 返回本人 L2 Case 的公开状态、预算和最终结果摘要。
         */
        PublicL2CaseSummary: {
            /** Case Id */
            case_id: string;
            /** Thread Id */
            thread_id: string;
            /** Related Order Id */
            related_order_id?: string | null;
            /** Issue Summary */
            issue_summary: string;
            /** Status */
            status: string;
            /** Stop Reason */
            stop_reason?: string | null;
            /** Trace State */
            trace_state: string;
            /** Context Policy Version */
            context_policy_version?: string | null;
            /** Failure Attribution */
            failure_attribution?: string | null;
            /** Steps Used */
            steps_used: number;
            /** Model Calls Used */
            model_calls_used: number;
            /** Tool Calls Used */
            tool_calls_used: number;
            /** Final Response */
            final_response?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PublicL2TraceEvent
         * @description 向用户公开不含 Prompt 和隐藏推理的 L2 动作轨迹。
         */
        PublicL2TraceEvent: {
            /** Sequence No */
            sequence_no: number;
            /** Payload Version */
            payload_version: number;
            /** Step Number */
            step_number: number;
            /** Event Type */
            event_type: string;
            /** Tool Category */
            tool_category?: string | null;
            /** Risk */
            risk?: string | null;
            /** Parameter Summary */
            parameter_summary?: {
                [key: string]: string;
            } | null;
            /** Result Code */
            result_code: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Duration Ms */
            duration_ms: number;
            context_summary?: components["schemas"]["L2ContextPublicSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PublicL2TracePage
         * @description 返回本人 Case 的稳定 keyset 公开 Trace 页面。
         */
        PublicL2TracePage: {
            /** Case Id */
            case_id: string;
            /** Trace State */
            trace_state: string;
            /** Events */
            events: components["schemas"]["PublicL2TraceEvent"][];
            /** Next After Sequence */
            next_after_sequence?: number | null;
            /** Has More */
            has_more: boolean;
        };
        /**
         * PublicL2UpgradePreview
         * @description 向浏览器披露 AI 身份、工具类别和固定预算的升级预览。
         */
        PublicL2UpgradePreview: {
            /** Preview Id */
            preview_id: string;
            /** Issue Summary */
            issue_summary: string;
            /** Related Order Id */
            related_order_id?: string | null;
            /** Context Categories */
            context_categories: string[];
            /** Allowed Tools */
            allowed_tools: string[];
            /** Max Steps */
            max_steps: number;
            /** Reads Confirmed Preferences */
            reads_confirmed_preferences: boolean;
            /**
             * Agent Identity
             * @default AI 二线客服，并非真人
             * @constant
             */
            agent_identity: "AI 二线客服，并非真人";
        };
        /**
         * PublicMemoryProposal
         * @description 展示待确认偏好具体内容，不允许客户端修改建议。
         */
        PublicMemoryProposal: {
            /** Proposal Id */
            proposal_id: string;
            /** Memory Type */
            memory_type: string;
            /** Value */
            value: string;
            /** Purpose */
            purpose: string;
        };
        /**
         * PublicOrder
         * @description 向浏览器返回当前账号有权查看的订单、物流和 Mock 交易摘要。
         */
        PublicOrder: {
            /** Order Id */
            order_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "shipped" | "delivered" | "cancelled";
            shipment?: components["schemas"]["PublicShipment"] | null;
            payment?: components["schemas"]["PublicPayment"] | null;
            /**
             * Refunds
             * @default []
             */
            refunds: components["schemas"]["PublicRefund"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PublicPayment
         * @description 向浏览器返回可展示但不可作为退款执行参数的 Mock 支付事实。
         */
        PublicPayment: {
            /** Payment Id */
            payment_id: string;
            /** Amount */
            amount: string;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
            /**
             * Channel
             * @enum {string}
             */
            channel: "mock_card" | "mock_wallet";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "settled" | "failed" | "refunded";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PublicRefund
         * @description 向浏览器返回已持久化 Mock 退款的只读验证摘要。
         */
        PublicRefund: {
            /** Refund Id */
            refund_id: string;
            /** Action Id */
            action_id: string;
            /** Amount */
            amount: string;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
            /**
             * Channel
             * @enum {string}
             */
            channel: "mock_card" | "mock_wallet";
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "succeeded" | "failed" | "unknown";
            /** Result Code */
            result_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PublicRefundPreview
         * @description 向浏览器展示服务端绑定的 Mock 退款审批内容。
         */
        PublicRefundPreview: {
            /** Action Id */
            action_id: string;
            /** Order Id */
            order_id: string;
            /** Reason Code */
            reason_code: string;
            /** Reason Detail */
            reason_detail: string;
            /** Amount */
            amount: string;
            /**
             * Currency
             * @constant
             */
            currency: "CNY";
            /**
             * Channel
             * @enum {string}
             */
            channel: "mock_card" | "mock_wallet";
            /**
             * Order Status
             * @enum {string}
             */
            order_status: "processing" | "shipped" | "delivered" | "cancelled";
            /** Shipment Status */
            shipment_status?: ("preparing" | "in_transit" | "delivered") | null;
            /**
             * Payment Status
             * @constant
             */
            payment_status: "settled";
            /**
             * Risk
             * @constant
             */
            risk: "R2";
            /** Citations */
            citations: components["schemas"]["PolicyCitation"][];
        };
        /**
         * PublicRefundResult
         * @description 向浏览器返回经过业务回读验证的 Mock 退款结果。
         */
        PublicRefundResult: {
            /** Action Id */
            action_id: string;
            /** Refund Id */
            refund_id?: string | null;
            /** Amount */
            amount: string;
            /** Status */
            status?: string | null;
            /** Verified */
            verified: boolean;
            /** Result Code */
            result_code: string;
        };
        /**
         * PublicShipment
         * @description 向浏览器返回不含内部主键和工作区信息的物流数据。
         */
        PublicShipment: {
            /**
             * Status
             * @enum {string}
             */
            status: "preparing" | "in_transit" | "delivered";
            /** Last Event */
            last_event: string;
            /** Estimated Delivery At */
            estimated_delivery_at?: string | null;
        };
        /**
         * RefundApprovalRequest
         * @description 只允许客户端提交服务端动作标识和批准或拒绝决定。
         */
        RefundApprovalRequest: {
            /** Action Id */
            action_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
        };
        /**
         * RefundsResponse
         * @description 返回指定私有订单的全部 Mock 退款只读摘要。
         */
        RefundsResponse: {
            /** Refunds */
            refunds: components["schemas"]["PublicRefund"][];
        };
        /**
         * RegisterRequest
         * @description 接收邀请注册所需的最小凭据。
         */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Invitation Code */
            invitation_code: string;
        };
        /**
         * RegistrationResponse
         * @description 返回邀请注册成功后的有限公开结果。
         */
        RegistrationResponse: {
            /** Username */
            username: string;
            /**
             * Status
             * @default registered
             * @constant
             */
            status: "registered";
        };
        /**
         * RetryRunRequest
         * @description 接收一次显式重试使用的新客户端请求 ID。
         */
        RetryRunRequest: {
            /** Client Message Id */
            client_message_id: string;
        };
        /**
         * RunAcceptedResponse
         * @description 返回已持久接受或幂等复用的 Agent Run 资源。
         */
        RunAcceptedResponse: {
            run: components["schemas"]["PublicAgentRun"];
            user_message: components["schemas"]["ConversationMessage"];
            /** Reused */
            reused: boolean;
        };
        /**
         * SessionCapabilities
         * @description 向前端公开当前模式下可展示的确定性能力。
         */
        SessionCapabilities: {
            /** Can Manage Orders */
            can_manage_orders: boolean;
            /** Can Manage Refunds */
            can_manage_refunds: boolean;
            /** Can Use Llm */
            can_use_llm: boolean;
        };
        /**
         * SessionResponse
         * @description 返回浏览器当前访问模式和内存态 CSRF Token。
         */
        SessionResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "guest" | "registered";
            /** Username */
            username?: string | null;
            /**
             * Session Scope
             * @enum {string}
             */
            session_scope: "browser" | "account";
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            capabilities: components["schemas"]["SessionCapabilities"];
        };
        /**
         * ShipmentInput
         * @description 校验创建或更新物流记录所需字段。
         */
        ShipmentInput: {
            /**
             * Status
             * @enum {string}
             */
            status: "preparing" | "in_transit" | "delivered";
            /** Last Event */
            last_event: string;
            /** Estimated Delivery At */
            estimated_delivery_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                lifecycle_status?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    send_chat_message_api_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_l2_api_conversations__thread_id__pending_l2_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingL2Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_l2_upgrade_api_conversations__thread_id__l2_upgrade_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["L2UpgradeDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_l2_memory_api_conversations__thread_id__l2_memory_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["L2MemoryDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_refund_api_conversations__thread_id__pending_refund_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRefundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_refund_api_conversations__thread_id__refund_approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lifecycle_api_conversations__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationLifecycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_conversations__thread_id__messages_get: {
        parameters: {
            query?: {
                after_sequence?: number;
                limit?: number;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_message_api_conversations__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsyncChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_conversations__thread_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_conversations__thread_id__runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_conversations__thread_id__runs__run_id__events_get: {
        parameters: {
            query?: {
                after_event_id?: number;
            };
            header?: never;
            path: {
                thread_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_l2_cases_api_l2_cases_get: {
        parameters: {
            query?: {
                thread_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["L2CasesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_l2_case_api_l2_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicL2CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_l2_case_trace_api_l2_cases__case_id__trace_get: {
        parameters: {
            query?: {
                after_sequence?: number;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicL2TracePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_api_memories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoriesResponse"];
                };
            };
        };
    };
    remove_memory_api_memories__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_api_memories__memory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCustomerPreference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersResponse"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_order_api_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_api_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_payment_api_orders__order_id__payment_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockPaymentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPayment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_refunds_api_orders__order_id__refunds_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
